### PR TITLE
feat: add AES encryption key generator

### LINKED ISSUE #66: Add AES encryption key generator
We use AES encryption in our codebase to encrypt stuff, And I see people regularly putting wrong keys. So add the AES key generator in dns.toys to make it easier for people to generate AES enc key.

### PR DESCRIPTION
**Pull request by dracarys18**
closes #66

### CODE REVIEW

**Comment by knadh** [comment]
Thanks for the PR @dracarys18. Just wondering, transmitting encryption keys that people may use in production, over plaintext UDP, is that a good idea? :cold_face:

**Comment by dracarys18** [comment]
Perhaps we can have something like [DNS over TLS](https://www.cloudflare.com/learning/dns/dns-over-tls/)

**Comment by knadh** [comment]
Adding HTTP/TLS + DNS defies the purpose of dns.toys though. For that, it's then just easier to setup an HTTP/TLS service that can just be curl'd.

**Comment by dracarys18** [comment]
Oh that makes sense! I guess we hit the wall here, Shall I close the PR then?

**Comment by knadh** [comment]
Yep, I think we should close this. While the PR on its own is perfectly fine, we shouldn't set the precedent of users copy-pasting and using encryption keys transmitted over an unencrypted channel.

**Pull request closed without merging**
