### PR TITLE
dictionary service

### LINKED ISSUE #16: Support for finding definitions and meanings of words
_Thanks for this. Recently started learning GO. Thought this might be a good exercise._

I worked on adding support for a dictionary service. So you can find definition of a word in different parts of speech like this - 

```
dig play.dictionary @dns.toys

play.                   1       IN      TXT     "noun:" "Activity for amusement only, especially among the young."
play.                   1       IN      TXT     "verb:" "To act in a manner such that one has fun; to engage in activities expressly for the purpose of recreation or entertainment."
```
Internally, it uses the API from https://dictionaryapi.dev/. Response from the API can be large with multiple meanings, and DNS packet size has limits, so the result from service is trimmed a bit to fetch one definition per part of speech.
 
A lot of reference for implementation was taken from the weather service.

It's on my forked repo at - [https://github.com/hold7door/dns.toys/tree/dictionary](url).

If you are okay with it, I'll submit a PR.

### PR DESCRIPTION
**Pull request by hold7door**
Dictionary with WordNet

```
dig play.dictionary @dns.toys

play.                   1       IN      TXT     "verb:" "contend against an opponent in a sport, game, or battle" "Princeton plays Yale this weekend"
play.                   1       IN      TXT     "verb:" "put (a card or piece) into play during a game, or act strategically as if in a card game" "He is playing his cards close to his chest"
play.                   1       IN      TXT     "noun:" "gay or light-hearted recreational activity for diversion or amusement" "it was all done in play"
play.                   1       IN      TXT     "noun:" "the act of playing for stakes in the hope of winning (including the payment of a price for a chance to win a prize)" "his gambling cost him a fortune"

```

Closes #16

### CODE REVIEW

**Comment by knadh** [comment]
Let's see if this gets merged https://github.com/lloyd/wnram/pull/3. If it does, then there's no need to do string parsing in this PR at all.

**Comment by knadh** [comment]
@hold7door don't think that PR is getting merged. Why don't you fork the repo and add `Look.NumRelations()`? Then, we can merge the PR.

**Comment by hold7door** [comment]
@knadh  yes, I tried contacting the owner, haven't received any response yet 

I have forked the repo, added `Look.NumRelations()` and updated the import.

**Comment by knadh** [comment]
This is now live. `dig fun.dict @dns.toys`.

Thanks for the great PR!

**Pull request merged**
